### ISSUE TITLE
Tyveri

### ISSUE THREAD

**Issue by pvnPL** [shenyaocn/IP-Camera-Bridge#1]
Jeg har ikke selv lavet dette i må meget gerne fjerne dette og så kan vil måske finde ud af noget men der er en ud tyv der her lavet dette slæt det mvh Peter Vedel Nielsen  8600 Silkeborg

**Comment by shenyaocn** [comment]
English please.

**Comment by pvnPL** [comment]
I don't jnow what this is - I have never seen/downloaded this app before. I have been a victim of Identity theft for not too long ago and that's of course why I am very careful with all my electronic devices and all the stuff on it.
Maybe you will let me see the pictures?

**Comment by shenyaocn** [comment]
Well, as a programming fanatics, there is no interest about your privacy 😁😁
**I am also very careful because I also have been a victim of Identity theft**

**Comment by pvnPL** [comment]
I dont Nov hi Der is som on the have been hagget again fuck does I have Der names
